### ISSUE TITLE
Mode: Quote is hardcoded in subscribe method

### ISSUE THREAD

**Issue by sharma-rohit** [zerodhatech/javakiteconnect#10]
In [this](https://github.com/zerodhatech/javakiteconnect/blob/master/kiteconnect/src/com/zerodhatech/ticker/KiteTicker.java#L396) line of the code, the mode is hardcoded to `modeQuote`.

Which makes setting the mode irrelevant.

**Comment by kssujithcj** [comment]
The default mode for subscription itself is modeQuote. The user has to subscribe for data and then setMode after that.
