### ISSUE TITLE
Tick.getTickTimestamp() and Tick.getLastTradedTime() inside setOnTickerArrivalListener always returns null

### ISSUE THREAD

**Issue by nuclearsagar** [zerodhatech/javakiteconnect#14]
As per example given below inside setOnTickerArrivalListener() 

```
System.out.println("tick timestamp date "+ticks.get(0).getTickTimestamp());
System.out.println("last traded time "+ticks.get(0).getLastTradedTime());

```
These 2 lines always return null.

**Comment by kssujithcj** [comment]
You need to check if tick size is greater than zero then only call getter methods.
Kite Ticker sends heartbeat ticks also which will only have one-byte data.

The last traded time is a field which is available only on full mode tick.
