### ISSUE TITLE
kiteSdk does not have requestAccessToken method

### ISSUE THREAD

**Issue by shahakash277** [zerodhatech/javakiteconnect#16]
// Get accessToken as follows,
User user =  kiteSdk.requestAccessToken("request_token", "your_apiSecret");

**Comment by kssujithcj** [comment]
From Kite Connect v3, the session generation is done using the generateSession method. You can check out the documentation [here](https://kite.trade/docs/javakiteconnect/v3/).
For technical queries, please use the Kite Connect [forum](https://kite.trade/forum).
