### ISSUE TITLE
kiteSdk does not have requestAccessToken method and userModel 

### ISSUE THREAD

**Issue by BhaveshSalunke** [zerodhatech/javakiteconnect#17]
kiteSdk.setAccessToken(userModel.accessToken);
kiteSdk.setPublicToken(userModel.publicToken);

**Comment by kssujithcj** [comment]
From Kite Connect v3, the session generation is done using the generateSession method. You can check out the documentation [here](https://kite.trade/docs/javakiteconnect/v3/).
For technical queries, please use the Kite Connect [forum](https://kite.trade/forum).
