### ISSUE TITLE
Thread local instance of SimpleDateFormat should be used.

### ISSUE THREAD

**Issue by kbsbng** [zerodhatech/javakiteconnect#5]
SimpleDateFormat is not thread safe.  Hence, we should be using a thread local instance of SimpleDateFormat.

https://github.com/zerodhatech/javakiteconnect/blob/014b744b594aff134d2cbaa30779b99d9d808e88/kiteconnect/src/com/zerodhatech/kiteconnect/KiteConnect.java#L55

**Comment by kssujithcj** [comment]
I have changed it to a local variable. You can download new jar from dist directory.
