### ISSUE TITLE
KiteTicker Java Reconnection Issue

### ISSUE THREAD

**Issue by StifflerPai1234** [zerodhatech/javakiteconnect#8]
Hi,

I have written following code for re-connection -

tickerProvider.setTryReconnection(true);
tickerProvider.setMaximumRetries(50);
tickerProvider.setMaximumRetryInterval(30);

But it is not working. Initially when we call KiteTicker connect() method we receive ticks properly. But once Internet Disconnected and then again Connected then reconnection not working. I recently updated to Kite API v3 and it is not working in v3 but in older version of API it was working properly.

I request you to please check this and help me as soon as possible.

Thanks

**Comment by kssujithcj** [comment]
Hi,
We have made changes to kite3 branch to fix this. You can use the latest jar file from dist directory of the repository. Let us know if you still face the same problem.
