### ISSUE TITLE
Please explain these lines

### ISSUE THREAD

**Issue by harshmoorjani** [zerodhatech/javakiteconnect#9]
https://github.com/zerodhatech/javakiteconnect/blob/66adc3ac18fc832ef7a11e60e66938793c84538a/kiteconnect/src/com/zerodhatech/ticker/KiteTicker.java#L455
```
int segment = x & 0xff;
int dec1 = (segment == NseCD) ? 10000000 : 100;
```
1. How are you getting if it's a currency derivative from these lines?
2. Why not considering `BseCD` too?

**Comment by kssujithcj** [comment]
Hi,
The segment is identified by a number (1-9) which can be seen in the constants. It is bit-shifted into the instrument_token.
In the above line, we're doing a bit shift and getting the segment ID.
We don't support BSE CDS yet.

**Comment by harshmoorjani** [comment]
Ok, so in simple terms... you are doing `mod 256` on `instrument_token`...

What I mean to understand is... how did you conclude that `segment = instrument_token % 256`?
Is this documented somewhere?

**Comment by knadh** [comment]
In the instrument CSV dump, there are two columns that you'll see, `exchange_token` and `instrument_token`. `exchange_token` is the original underlying token directly obtained from the exchange and `instrument_token` is our bit-shifted version that includes the segment information as well.

`instrument_token = (exchange_token << 8) + segment_id`

This is abstracted away and you don't generally need to dissect the `instrument_token` to interact with the APIs.

**Comment by harshmoorjani** [comment]
Sure. Understood.

I was directly interacting with HTTP API and using this SDK as reference, hence stumbled upon this.

Thanks
